language: python
python:
  - "2.7"
  - "3.6"
install:
  - easy_install vsc-install
script:
  # 'hpcugent' is a mandatory remote for setup.py to work (because of vsc-install)
  - git remote add hpcugent https://github.com/hpcugent/vsc-mympirun.git
  - python setup.py test
